import {
  SlashCommandBuilder,
  ChatInputCommandInteraction,
  EmbedBuilder,
  PermissionFlagsBits,
} from 'discord.js';
import ReferralService from '../services/referralService.js';

export const adminReferralCommand = {
  data: new SlashCommandBuilder()
    .setName('admin-referral')
    .setDescription('[STAFF ONLY] Inspect referral lineage, invite codes, and status for a member.')
    .setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
    .addUserOption((option) =>
      option.setName('user').setDescription('Target member to inspect').setRequired(true)
    ),

  async execute(interaction: ChatInputCommandInteraction) {
    await interaction.deferReply({ ephemeral: true });

    if (!interaction.memberPermissions?.has(PermissionFlagsBits.ManageGuild)) {
      await interaction.editReply({
        content: '❌ You lack staff permissions (Manage Guild) to execute this command.',
      });
      return;
    }

    const targetUser = interaction.options.getUser('user', true);
    const data = await ReferralService.inspectReferral(targetUser.id);

    if (!data || !data.user) {
      await interaction.editReply({
        content: `ℹ️ No database records found for member @${targetUser.username} (${targetUser.id}).`,
      });
      return;
    }

    const embed = new EmbedBuilder()
      .setTitle(`🔎 Referral Inspection: @${targetUser.username}`)
      .setColor(0x8b5cf6)
      .addFields(
        { name: 'Discord ID', value: `\`${data.user.discordId}\``, inline: true },
        { name: 'Current Total XP', value: `**${data.user.xp.toLocaleString()} XP**`, inline: true },
        { name: 'Account First Seen', value: new Date(data.user.createdAt).toLocaleString(), inline: true }
      );

    // As Invitee Details
    if (data.asInvitee) {
      embed.addFields(
        {
          name: '📥 How They Joined',
          value: [
            `**Status:** \`${data.asInvitee.status}\``,
            `**Inviter:** ${data.asInvitee.inviter ? `@${data.asInvitee.inviter.username} (\`${data.asInvitee.inviter.discordId}\`)` : 'None / Direct Join'}`,
            `**Invite Code:** \`${data.asInvitee.inviteCode || 'N/A'}\``,
            `**Joined At:** ${new Date(data.asInvitee.joinedAt).toLocaleString()}`,
            `**Verified At:** ${data.asInvitee.verifiedAt ? new Date(data.asInvitee.verifiedAt).toLocaleString() : 'Not verified yet'}`,
            `**Rewarded At:** ${data.asInvitee.rewardedAt ? new Date(data.asInvitee.rewardedAt).toLocaleString() : 'Not rewarded'}`,
          ].join('\n'),
          inline: false,
        }
      );
    } else {
      embed.addFields({
        name: '📥 How They Joined',
        value: 'Direct server join or joined prior to invite tracker setup.',
        inline: false,
      });
    }

    // Referrals Made By Them
    embed.addFields({
      name: '📤 Referrals Generated By Member',
      value: [
        `**Successful (Verified):** ${data.referralsGiven.successfulCount}`,
        `**Pending Verification:** ${data.referralsGiven.pendingCount}`,
        `**Total Referral XP Generated:** ${data.referralsGiven.referralXpEarned.toLocaleString()} XP`,
      ].join('\n'),
      inline: false,
    });

    embed.setFooter({ text: 'UPRISE Staff Audit Tools' }).setTimestamp(new Date());

    await interaction.editReply({ embeds: [embed] });
  },
};

export default adminReferralCommand;
